name: Publish
on:
    workflow_dispatch:
jobs:
    publish:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - run:  ls
            - name: basic setup
              uses: ./.github/actions/basic_setup
            - run:  rm -fr dist/
            - run:  uv build --wheel
            - run:  uv publish --token ${{ secrets.PUBLISH_TOKEN }}
