name: Tests
on:
  pull_request:
jobs:
  Unit-Tests:
    runs-on: ubuntu-20.04
    steps:
      - name: check out our code
        uses: actions/checkout@v2
      - name: install poetry
        run:  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: install testix
        run:  poetry install
      - name: unit tests
        run:  poetry run rake units
  Run-Examples:
    runs-on: ubuntu-20.04
    steps:
      - name: check out our code
        uses: actions/checkout@v2
      - name: install poetry
        run:  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: install testix
        run:  poetry install
      - name: examples
        run:  poetry run rake examples
  Generate-Wheel:
    runs-on: ubuntu-20.04
    steps:
      - name: check out our code
        uses: actions/checkout@v2
      - name: install poetry
        run:  curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: build wheel
        run:  poetry build -f wheel
  All-OK:
    runs-on: ubuntu-20.04
    needs:
        - Generate-Wheel
        - Unit-Tests
        - Run-Examples
    if: always()
    steps:
      - name: check out our code
        uses: actions/checkout@v2
      - name: verify we did not forget any tests
        run:  rake all_tests_included
      - name: Generate-Wheel
        run:  rake 'enforce_success[${{needs.Generate-Wheel.result}}]'
      - name: Unit-Tests
        run:  rake 'enforce_success[${{needs.Unit-Tests.result}}]'
      - name: Run-Examples
        run:  rake 'enforce_success[${{needs.Run-Examples.result}}]'
